# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[local]
[local.global.parameters]
stack_name = "schedule-reminder"

[local.build.parameters]
cached = true
parallel = true

[local.validate.parameters]
lint = true

[local.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = [
  "Environment=local",
  "AwsEndpointUrl=http://localstack:4566",
  "ParamPathPrefix=/lambda-functions/schedule-reminder",
]

[local.package.parameters]
resolve_s3 = true

[local.local_start_lambda.parameters]
warm_containers = "EAGER"

[local.local_invoke.parameters]
container_host = "dind"
container_host_interface = "0.0.0.0"

[prod]
[prod.global.parameters]
stack_name = "schedule-reminder-deploy-stack"

[prod.build.parameters]
cached = false
parallel = true

[prod.validate.parameters]
lint = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true

[prod.package.parameters]
resolve_s3 = true

[prod.local_start_lambda.parameters]
warm_containers = "EAGER"
